name: buisness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  gsheets: 
  http: ^1.2.2
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
